### ISSUE TITLE
CodiMD Plugin

### ISSUE THREAD

**Issue by robertfels** [0140454/codimd-book#1]
Hi 0140454

It would be great to have this as a plugin directly on the system so that it is available to all users without having an extra browser extension. Do you think that would be possible?
And by the way: good work!

Best
Robert

**Comment by 0140454** [comment]
Do you mean that you wish it to be available in every Chrome profile automatically?
If yes, you can follow the [documentation](https://developer.chrome.com/docs/extensions/mv2/external_extensions/#preferences) to make it installed in every Chrome profile automatically.

_/usr/share/google-chrome/extensions/apahkbcjkfpaknjebpaoaehpjiedeapa,json_
```
{
    "external_update_url": "https://clients2.google.com/service/update2/crx"
}
```

**Comment by robertfels** [comment]
No i mean in CodiMD

**Comment by 0140454** [comment]
Currently, there is no plan to integrate it into CodiMD.

If you want to use book mode without extension, HackMD may be your best option.
